project_id = "kvygdphglkxqtaoxlzmh"

[functions.check-phone-exists]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.verify-face]
verify_jwt = true

[functions.phone-login]
verify_jwt = false

[functions.send-email-otp]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false

[functions.email-login]
verify_jwt = false
